[features]
seeds = false
skip-lint = false
[programs.devnet]
vaporspacegrid = "6nKzKeV6BkjpvtB5uyEGgbWgxnFKqX1n38J8NLG4o2CT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/sarahagarrat/.config/solana/id.json"

[scripts]
test = "node tests/vaporspacegrid.js"